# TO USE THIS FILE on Windows:
# 1. Install Oracle VirtualBox (free software)
# 2. Install Hashicorp Vagrant (free software)
# 3. cd to the directory where this file is
# 4. run "vagrant up"

## Set the login

# vagrant ssh
# sudo passwd vagrant
# Set the password

## Launch Oracle VirtualBox (in graphical mode) and connect to the VM that Vagrant created.
# >Login: vagrant
# >Password: (whatever you set above)

## Run the game
# startxfce4
# Start a Bash Prompt
# Run "cd /space-nerds/space-nerds-in-space-master/;./snis_launcher"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1804"

# config.ssh.username = 'root'
# config.ssh.password = 'vagrant'
# config.ssh.insert_key = 'true'

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
config.vm.provision "shell", inline: <<-SHELL

apt-get update

# Install dependencies
apt-get install build-essentials portaudio19-dev libvorbis-dev libgtk2.0-dev libgtkglext1-dev liblua5.2-dev libglew1.5-dev lua5.3 apt-get install libssl-dev git
# apt-get install libttspico-utils; # for text to speech
# apt-get install sox; # for "play" command, used by text to speech

# # Install game
# apt-get install git make;
# git clone https://github.com/smcameron/space-nerds-in-space.git /space-nerds;
git clone https://github.com/HarrisonTotty/space-nerds-in-space.git /space-nerds;

# Build the game
cd /space-nerds; make;
cd /space-nerds; make update-assets;

# Install graphical interface and Virtual Box guest additions
apt-get install -y xfce4 xfce4-session
apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11

SHELL

end
